services:
    db:
        image: postgres:16
        container_name: postgres_edms
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
        volumes:
            - pgdata:/var/lib/postgresql/data

    edms:
        build: .
        image: zinox/nse-edms
        container_name: nse_edms
        ports:
            - "${APP_PORT:-8080}:8080"
        # environment:
        #     - NUXEO_CLID=${PROJECT_CLID}
        #     - NUXEO_DB_TYPE=postgresql
        #     - NUXEO_TEMPLATES=default,postgresql
        #     - NUXEO_DB_HOST=db
        #     - NUXEO_DB_USER=${PG_USER}
        #     - NUXEO_DB_PASSWORD=${PG_PASSWORD}
        #     - NUXEO_DB_NAME=${PG_DB}
        #     - NUXEO_DEV=true
        volumes:
            - edms_data:/var/lib/edms
            - edms_logs:/var/log/edms
            - ./nse.conf:/etc/edms/conf.d/nse.conf:ro
        depends_on:
            db:
                condition: service_healthy

volumes:
    pgdata:
    edms_data:
    edms_logs:
