name: NSE_EDMS
version: "2"

services:
    db:
        image: postgres:16
        container_name: postgres_database
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
        volumes:
            - pgdata:/var/lib/postgresql/data

    edms:
        build: .
        image: zinox/nse-edms
        container_name: nse_edms
        ports:
            - "${APP_PORT:-8080}:8080"
        environment:
            #     - NUXEO_CLID=${PROJECT_CLID}
            - NUXEO_DEV=false
        volumes:
            - edms_data:${EDMS_DATA_PATH}
            - edms_logs:${EDMS_LOGS_PATH}
            # - ./config/nse.conf:${EDMS_CONF_PATH}/conf.d/nse.conf:ro
        depends_on:
            db:
                condition: service_healthy

volumes:
    pgdata:
    edms_data:
    edms_logs:
