name: NSE_EDMS_PROD
services:
    db:
        image: postgres:16
        container_name: prod_postgres_database
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
        volumes:
            - pgdata:/var/lib/postgresql/data

    elasticsearch:
        image: elasticsearch:8.19.7
        container_name: prod_elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "8200:9200"
            - "8300:9300"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl --silent --fail localhost:9200/_cluster/health || exit 1",
                ]
            interval: 10s
            timeout: 10s
            retries: 5
    edms:
        image: zinoxtech/nse_edms:v6
        container_name: prod_edms_software
        ports:
            - "${APP_PORT:-8080}:8080"
        environment:
            - EDMS_DEV=false
        volumes:
            - edms_data:${EDMS_DATA_PATH}
            - edms_logs:${EDMS_LOGS_PATH}
            - ./config/custom.conf:${EDMS_CONF_PATH}/conf.d/custom.conf:ro
        depends_on:
            db:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy

    nginx:
        image: nginx:alpine
        container_name: prod_nginx_proxy
        ports:
            - "6080:80"
            - "6443:443"
        environment:
            - DOMAIN=${DOMAIN_NAME}
            - CERT_NAME=${DOMAIN_NAME}
            - UPSTREAM=edms
            - APP_PORT=${APP_PORT:-8080}
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh
            - ./nginx/secure/:/etc/nginx/templates/
        depends_on:
            edms:
                condition: service_started

    certbot:
        image: certbot/certbot
        container_name: prod_certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
volumes:
    pgdata:
    edms_data:
    edms_logs:
    elasticsearch-data:
