nuxeo.url=http://localhost:8080/edms
org.nuxeo.ecm.contextPath=/edms
nuxeo.webapp.contextPath=/edms
nuxeo.web.ui.app.title=NSE EDMS
org.nuxeo.ecm.product.name=NSE EDMS

# nuxeo.db.name=edmsdb
# nuxeo.db.user=nseedms
# nuxeo.db.password=edms_password
# nuxeo.db.host=localhost
# nuxeo.db.port=5432
# nuxeo.db.type=postgresql

# nuxeo.templates=default,postgresql
