events {
    worker_connections 1024;
}

http {
    # 1. Redirect HTTP to HTTPS
    server {
        listen 80 default_server;
        server_name $DOMAIN www.$DOMAIN;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. HTTPS Server
    server {
        listen 443 ssl;
        server_name $DOMAIN www.$DOMAIN;

        ssl_certificate /etc/letsencrypt/live/$CERT_NAME/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$CERT_NAME/privkey.pem;

        client_max_body_size 100M;

        location / {
            proxy_pass http://$UPSTREAM:$APP_PORT;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}